//go:build amd64 && !purego

package amd64

// Assembly function declarations - implemented in avx512_test_amd64.s
// These functions are generated by gen_avx512.go using bavard.

// testVALIGND tests VALIGND instruction
func testVALIGND(src1, src2 *[16]uint32, imm uint64, dst *[16]uint32)

// testVALIGNQ tests VALIGNQ instruction
func testVALIGNQ(src1, src2 *[8]uint64, imm uint64, dst *[8]uint64)

// testVPBLENDMQ tests VPBLENDMQ instruction
func testVPBLENDMQ(src1, src2 *[8]uint64, mask uint64, dst *[8]uint64)

// testVPBLENDMD tests VPBLENDMD instruction
func testVPBLENDMD(src1, src2 *[16]uint32, mask uint64, dst *[16]uint32)

// testVPERMQ tests VPERMQ instruction
func testVPERMQ(src *[8]uint64, imm uint64, dst *[8]uint64)

// testVPERMD tests VPERMD instruction
func testVPERMD(idx, src *[16]uint32, dst *[16]uint32)

// testVPERMI2Q tests VPERMI2Q instruction
func testVPERMI2Q(src1, idx, src2 *[8]uint64, dst *[8]uint64)

// testVPERMT2Q tests VPERMT2Q instruction
func testVPERMT2Q(src1, idx, src2 *[8]uint64, dst *[8]uint64)

// testVSHUFI64X2 tests VSHUFI64X2 instruction
func testVSHUFI64X2(src1, src2 *[8]uint64, imm uint64, dst *[8]uint64)

// testVSHUFPD tests VSHUFPD instruction
func testVSHUFPD(src1, src2 *[8]uint64, imm uint64, dst *[8]uint64)

// testVPSHUFD tests VPSHUFD instruction
func testVPSHUFD(src *[16]uint32, imm uint64, dst *[16]uint32)

// testVPUNPCKLDQ tests VPUNPCKLDQ instruction
func testVPUNPCKLDQ(src1, src2 *[16]uint32, dst *[16]uint32)

// testVPUNPCKHDQ tests VPUNPCKHDQ instruction
func testVPUNPCKHDQ(src1, src2 *[16]uint32, dst *[16]uint32)

// testVPUNPCKLQDQ tests VPUNPCKLQDQ instruction
func testVPUNPCKLQDQ(src1, src2 *[8]uint64, dst *[8]uint64)

// testVPUNPCKHQDQ tests VPUNPCKHQDQ instruction
func testVPUNPCKHQDQ(src1, src2 *[8]uint64, dst *[8]uint64)

// testVPMADD52LUQ tests VPMADD52LUQ instruction (IFMA)
func testVPMADD52LUQ(a, b, c *[8]uint64, dst *[8]uint64)

// testVPMADD52HUQ tests VPMADD52HUQ instruction (IFMA)
func testVPMADD52HUQ(a, b, c *[8]uint64, dst *[8]uint64)

// testVPTERNLOGD tests VPTERNLOGD instruction
func testVPTERNLOGD(a, b, c *[16]uint32, imm uint64, dst *[16]uint32)
